name: CI Pipeline with Hadolint (all Dockerfiles)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'Dockerfile*'

permissions:
  contents: read
  security-events: write
  pull-requests: write
  actions: write


jobs:
  hadolint-sarif-report:
    name: Generate and Upload SARIF Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Hadolint
        run: |
          sudo wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          sudo chmod +x /usr/local/bin/hadolint

      - name: Generate Hadolint SARIF report
        run: |
          find . -type f -name "Dockerfile*" -print0 | xargs -0 -r hadolint --format sarif > hadolint-report.sarif || true
      
      - name: Upload SARIF file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: hadolint-sarif-report
          path: hadolint-report.sarif
          
      - name: Upload SARIF report to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-report.sarif