name: CI Pipeline with Hadolint (all Dockerfiles)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'Dockerfile*'

permissions:
  contents: read
  security-events: write
  pull-requests: write
  actions: write


jobs:
  find-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      dockerfiles_matrix: ${{ steps.set_matrix.outputs.dockerfiles }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find all Dockerfiles and create JSON array
        id: set_matrix
        run: |
          DOCKERFILES=$(find . -type f -name "Dockerfile*" | jq -R -s -c 'split("\n")[:-1]')
          echo "dockerfiles=$DOCKERFILES" >> "$GITHUB_OUTPUT"
          echo $DOCKERFILES

  hadolint-report:
    name: Lint ${{ matrix.dockerfile }}
    needs: find-dockerfiles
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile: ${{ fromJson(needs.find-dockerfiles.outputs.dockerfiles_matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Hadolint Action
        id: hadolint_step
        continue-on-error: true
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          format: sarif
          output-file: hadolint-report.sarif

      - name: Upload SARIF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hadolint-sarif-report-${{ matrix.dockerfile }}
          path: hadolint-report.sarif

      - name: Upload SARIF report to GitHub Security
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const sarif = fs.readFileSync(`hadolint-report.sarif`, 'utf8');
            await github.rest.codeScanning.uploadSarif({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              ref: context.ref,
              sarif: Buffer.from(sarif).toString('base64'),
              checkout_uri: `file://${process.env.GITHUB_WORKSPACE}`,
              tool_name: 'hadolint'
            });
            env:
              MATRIX_DOCKERFILE: ${{ matrix.dockerfile }}

      

