name: CI Pipeline with Hadolint (all Dockerfiles)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'Dockerfile*'

permissions:
  contents: read
  security-events: write
  pull-requests: write
  actions: write

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find all Dockerfiles
        id: find-dockerfiles
        run: |
          # Use find to locate all Dockerfiles and create a compact JSON array
          DOCKERFILES=$(find . -name "Dockerfile*" -not -path "./.git/*" -not -path "./vendor/*" | jq -R . | jq -cs .)
          echo "dockerfiles=${DOCKERFILES}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Lint all Dockerfiles with Hadolint and generate SARIF report
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfiles: ${{ steps.find-dockerfiles.outputs.dockerfiles }}
          output-file: hadolint-report.sarif
          format: "sarif"
          token: ${{ secrets.GITHUB_TOKEN }}
          failure-threshold: "info"
        continue-on-error: true

      # Upload the SARIF report as an artifact for later inspection or integration with code scanning tools
      - name: Upload SARIF report
        uses: actions/upload-artifact@v4
        with:
          name: hadolint-sarif-report
          path: hadolint-report.sarif
          retention-days: 7