name: CI Pipeline with Trivy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 4' # Every Thursday at 13:00 UTC
  push:
    branches:
      - dev
    paths:
      - 'Dockerfile'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
    paths:
      - 'Dockerfile'

jobs:
  build-and-scan-main:
    name: Build and Scan main Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile -t ecommerce-main:ci .

      - name: Get short Git commit SHA
        id: vars
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scanner on the built image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ecommerce-main:ci
          format: 'sarif'
          output: trivy-main-results.sarif
          severity: 'CRITICAL,HIGH'
          build-args: |
            GIT_SHA=${{ steps.vars.outputs.SHA_SHORT }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-main-results.sarif

  